// Mocks generated by Mockito 5.4.0 from annotations
// in honkai_assistance/test/data/repositories/remote_repositories_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:honkai_assistance/common/error/error.dart' as _i5;
import 'package:honkai_assistance/domain/entities/changelog_entity.dart'
    as _i18;
import 'package:honkai_assistance/domain/entities/character_banner_entity.dart'
    as _i9;
import 'package:honkai_assistance/domain/entities/character_entity.dart'
    as _i12;
import 'package:honkai_assistance/domain/entities/elf_banner_entity.dart'
    as _i11;
import 'package:honkai_assistance/domain/entities/elf_entity.dart' as _i13;
import 'package:honkai_assistance/domain/entities/equipment_banner_entity.dart'
    as _i10;
import 'package:honkai_assistance/domain/entities/event_entity.dart' as _i8;
import 'package:honkai_assistance/domain/entities/guide_entity.dart' as _i19;
import 'package:honkai_assistance/domain/entities/news_update_entity.dart'
    as _i7;
import 'package:honkai_assistance/domain/entities/outfit_entity.dart' as _i16;
import 'package:honkai_assistance/domain/entities/redeem_code_entity.dart'
    as _i6;
import 'package:honkai_assistance/domain/entities/stigmata_entity.dart' as _i14;
import 'package:honkai_assistance/domain/entities/tier_list_entity.dart'
    as _i17;
import 'package:honkai_assistance/domain/entities/weapon_entity.dart' as _i15;
import 'package:honkai_assistance/domain/repositories/remote_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteRepository extends _i1.Mock implements _i3.RemoteRepository {
  MockRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RedeemCodeEntity>>>
      getRedeemCode() => (super.noSuchMethod(
            Invocation.method(
              #getRedeemCode,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.RedeemCodeEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.RedeemCodeEntity>>(
              this,
              Invocation.method(
                #getRedeemCode,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.RedeemCodeEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.NewsUpdateEntity>>>
      getNewsUpdate() => (super.noSuchMethod(
            Invocation.method(
              #getNewsUpdate,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i7.NewsUpdateEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.NewsUpdateEntity>>(
              this,
              Invocation.method(
                #getNewsUpdate,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.NewsUpdateEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.EventEntity>>> getEvent() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvent,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.EventEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.EventEntity>>(
          this,
          Invocation.method(
            #getEvent,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.EventEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.CharacterBannerEntity>>>
      getCharacterBanner() => (super.noSuchMethod(
            Invocation.method(
              #getCharacterBanner,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i9.CharacterBannerEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.CharacterBannerEntity>>(
              this,
              Invocation.method(
                #getCharacterBanner,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i9.CharacterBannerEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.EquipmentBannerEntity>>>
      getEquipmentBanner() => (super.noSuchMethod(
            Invocation.method(
              #getEquipmentBanner,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i10.EquipmentBannerEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i10.EquipmentBannerEntity>>(
              this,
              Invocation.method(
                #getEquipmentBanner,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i10.EquipmentBannerEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.ElfBannerEntity>>>
      getElfBanner() => (super.noSuchMethod(
            Invocation.method(
              #getElfBanner,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i11.ElfBannerEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i11.ElfBannerEntity>>(
              this,
              Invocation.method(
                #getElfBanner,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i11.ElfBannerEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.CharacterEntity>>>
      getCharacter() => (super.noSuchMethod(
            Invocation.method(
              #getCharacter,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i12.CharacterEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i12.CharacterEntity>>(
              this,
              Invocation.method(
                #getCharacter,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i12.CharacterEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i13.ElfEntity>>> getElf() =>
      (super.noSuchMethod(
        Invocation.method(
          #getElf,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i13.ElfEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i13.ElfEntity>>(
          this,
          Invocation.method(
            #getElf,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i13.ElfEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i14.StigmataEntity>>>
      getStigmata() => (super.noSuchMethod(
            Invocation.method(
              #getStigmata,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i14.StigmataEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i14.StigmataEntity>>(
              this,
              Invocation.method(
                #getStigmata,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i14.StigmataEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i15.WeaponEntity>>> getWeapon() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeapon,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i15.WeaponEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i15.WeaponEntity>>(
          this,
          Invocation.method(
            #getWeapon,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i15.WeaponEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i16.OutfitEntity>>> getOutfit() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutfit,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i16.OutfitEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i16.OutfitEntity>>(
          this,
          Invocation.method(
            #getOutfit,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i16.OutfitEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i17.TierListEntity>>>
      getTierList() => (super.noSuchMethod(
            Invocation.method(
              #getTierList,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i17.TierListEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i17.TierListEntity>>(
              this,
              Invocation.method(
                #getTierList,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i17.TierListEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i18.ChangelogEntity>>>
      getChangelog() => (super.noSuchMethod(
            Invocation.method(
              #getChangelog,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i18.ChangelogEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i18.ChangelogEntity>>(
              this,
              Invocation.method(
                #getChangelog,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i18.ChangelogEntity>>>);
  @override
  _i4.Future<
      _i2
          .Either<_i5.Failure, List<_i19.GuideEntity>>> getBeginnerGuide() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBeginnerGuide,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i19.GuideEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i19.GuideEntity>>(
          this,
          Invocation.method(
            #getBeginnerGuide,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i19.GuideEntity>>>);
  @override
  _i4.Future<
      _i2
          .Either<_i5.Failure, List<_i19.GuideEntity>>> getGeneralGuide() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGeneralGuide,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i19.GuideEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i19.GuideEntity>>(
          this,
          Invocation.method(
            #getGeneralGuide,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i19.GuideEntity>>>);
}
